### PR TITLE
fix: Fix compilation and rendering on macOS

### LINKED ISSUE #185: Cannot build on macOS (undefined identifier _font)
Hey!

I'm trying to use package on my rn-macos app and when I hit compile I get the following errors:

Screenshot 2020-12-15 at 21 20 23

Any idea what might be going on?

### PR DESCRIPTION
**Pull request by ospfranco**
This fixes #185 

1. Fixes compilation on macOS the _font property was overwriting some other inherited property and that was causing troubles
2. Fixes the height to be closer to the native component real height, otherwise rendering is very broken

### CODE REVIEW

File: macos/RNCPicker.m [hunk 1]
```diff
@@ -20,11 +20,11 @@ - (instancetype)initWithFrame:(CGRect)frame
 {
     if ((self = [super initWithFrame:frame pullsDown:false])) {
         _color = [NSColor blackColor];
-        _font  = [NSFont systemFontOfSize:21];
+        _customFont  = [NSFont systemFontOfSize:14];
```
Comment (shirakaba) [inline macos/RNCPicker.m:23]: Curious why renaming `_font` to `_customFont` fixes it.

Comment (ospfranco) [reply macos/RNCPicker.m:23]: font is an inherited property of the pop up

**Comment by ospfranco** [comment]
Oh man... this thing is very very broken, please don't merge it yet, it seems the initial selected value is not correctly passed to the native component

**Review by Naturalclar — APPROVED** [review]
@ospfranco thanks for working on this!
confirmed that this fix builds successfully and changes the height of the picker component.

> it seems the initial selected value is not correctly passed to the native component

I've also confirmed that this is happening, but it's orthogonal to this issue and it should be fixed in a separate PR.

**Comment by ospfranco** [comment]
@Naturalclar thanks for merging, would you mind taking a look into the initial value issue? I'm not a obj-c developer at all, so far all the patches I've been able to make are just through random changing of things
